// No whitespace allowed between digits
integer = @{ ASCII_DIGIT+ }

atom = _{ integer }

bin_op = _{ add | subtract | multiply | divide }
    add = { "+" }
    subtract = { "-" }
    multiply = { "*" }
    divide = { "/" }

expr = { atom ~ (bin_op ~ atom)* }

WHITESPACE = _{ " " }

// We can't have SOI and EOI on expr directly, because it is used
// recursively (e.g. with parentheses)
equation = { SOI ~ expr ~ EOI }

coefficient = { SOI ~ expr ~ EOI }
